pub(crate) const SERVICE_INFO: &'static [(&'static str, &'static [(&'static str, &'static [&'static str])])] = [
    ("AirQuality", [
        ("aqi", ["latitude", "longitude"].as_slice()),
        ("qualityIndex", ["latitude", "longitude"].as_slice()),
        ("qualityIndexByZipCode", ["zipCode"].as_slice()),
    ].as_slice()),
    ("Alcohol Consumption", [
        ("getAllCountryValues", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValueLitresPerCapita15", ["Country"].as_slice()),
        ("getYEA", ["Country"].as_slice()),
        ("getYear", ["Country"].as_slice()),
    ].as_slice()),
    ("Alexa", [
        ("createSkill", ["configuration"].as_slice()),
        ("deleteSkill", ["ID"].as_slice()),
        ("getSkill", ["ID"].as_slice()),
        ("getSkillCategories", [].as_slice()),
        ("getSlotTypes", [].as_slice()),
        ("invokeSkill", ["ID", "utterance"].as_slice()),
        ("listSkills", [].as_slice()),
        ("updateSkill", ["ID", "configuration"].as_slice()),
    ].as_slice()),
    ("Autograders", [
        ("createAutograder", ["configuration"].as_slice()),
        ("getAutograderConfig", ["name"].as_slice()),
        ("getAutograders", [].as_slice()),
    ].as_slice()),
    ("Avoidable Death", [
        ("getAllVariableValues", [].as_slice()),
        ("getCountry", ["Variable"].as_slice()),
        ("getDeathPer100000", ["Variable"].as_slice()),
        ("getMeasure", ["Variable"].as_slice()),
        ("getYear", ["Variable"].as_slice()),
    ].as_slice()),
    ("BaseX", [
        ("command", ["url", "command", "username", "password"].as_slice()),
        ("query", ["url", "database", "query", "username", "password"].as_slice()),
    ].as_slice()),
    ("Battleship", [
        ("allShips", [].as_slice()),
        ("fire", ["row", "column"].as_slice()),
        ("placeShip", ["ship", "row", "column", "facing"].as_slice()),
        ("remainingShips", ["roleID"].as_slice()),
        ("reset", [].as_slice()),
        ("shipLength", ["ship"].as_slice()),
        ("start", [].as_slice()),
    ].as_slice()),
    ("BingTraffic", [
        ("search", ["westLongitude", "northLatitude", "eastLongitude", "southLatitude"].as_slice()),
        ("stop", [].as_slice()),
    ].as_slice()),
    ("CARES data", [
        ("get1222021", ["Well A"].as_slice()),
        ("get172", ["Well A"].as_slice()),
        ("getAllWellAValues", [].as_slice()),
        ("getTable", [].as_slice()),
    ].as_slice()),
    ("COVID-19", [
        ("getConfirmedCounts", ["country", "state", "city"].as_slice()),
        ("getDeathCounts", ["country", "state", "city"].as_slice()),
        ("getLocationCoordinates", ["country", "state", "city"].as_slice()),
        ("getLocationsWithData", [].as_slice()),
        ("getRecoveredCounts", ["country", "state", "city"].as_slice()),
        ("getVaccinationCategories", [].as_slice()),
        ("getVaccinationCountries", [].as_slice()),
        ("getVaccinationData", ["country", "state", "category", "startDate", "endDate"].as_slice()),
        ("getVaccinationStates", [].as_slice()),
    ].as_slice()),
    ("COVID-19 Estimated ICU Beds", [
        ("getAllStateValues", [].as_slice()),
        ("getCollectionDate", ["state"].as_slice()),
        ("getCountLL", ["state"].as_slice()),
        ("getCountUL", ["state"].as_slice()),
        ("getGeocodedStateForState", ["state"].as_slice()),
        ("getPercentageLL", ["state"].as_slice()),
        ("getPercentageOfStaffedAdultICUBedsOccupiedEstimated", ["state"].as_slice()),
        ("getPercentageUL", ["state"].as_slice()),
        ("getStaffedAdultICUBedsOccupiedEstimated", ["state"].as_slice()),
        ("getTable", [].as_slice()),
        ("getTotalLL", ["state"].as_slice()),
        ("getTotalStaffedAdultICUBeds", ["state"].as_slice()),
        ("getTotalUL", ["state"].as_slice()),
    ].as_slice()),
    ("COVID-19 ICU Bed", [
        ("getAllStateValues", [].as_slice()),
        ("getCollectionDate", ["state"].as_slice()),
        ("getPercentageOfStaffedAdultICUBedsOccupiedEstimated", ["state"].as_slice()),
        ("getStaffedAdultICUBedsOccupiedEstimated", ["state"].as_slice()),
        ("getTable", [].as_slice()),
        ("getTotalStaffedAdultICUBeds", ["state"].as_slice()),
    ].as_slice()),
    ("CS PhDs By Ethnicity", [
        ("getAsianByYear", [].as_slice()),
        ("getAsianColumn", [].as_slice()),
        ("getBlackByYear", [].as_slice()),
        ("getBlackColumn", [].as_slice()),
        ("getHispanicByYear", [].as_slice()),
        ("getHispanicColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["Year", "column name"].as_slice()),
        ("getWhiteByYear", [].as_slice()),
        ("getWhiteColumn", [].as_slice()),
        ("getYearColumn", [].as_slice()),
    ].as_slice()),
    ("Cape Grim CO2", [
        ("getAllCO2PpmValues", [].as_slice()),
        ("getAllDATEValues", [].as_slice()),
        ("getCO2Ppm", ["DATE"].as_slice()),
        ("getRecord", ["DATE"].as_slice()),
    ].as_slice()),
    ("Chart", [
        ("defaultOptions", [].as_slice()),
        ("draw", ["lines", "options"].as_slice()),
        ("drawBarChart", ["dataset", "xAxisTag", "yAxisTag", "datasetTag", "title"].as_slice()),
        ("drawLineChart", ["dataset", "xAxisTag", "yAxisTag", "datasetTag", "title"].as_slice()),
    ].as_slice()),
    ("Climate Forcings", [
        ("getAerosolsByYear", [].as_slice()),
        ("getAerosolsColumn", [].as_slice()),
        ("getAllByYear", [].as_slice()),
        ("getAllColumn", [].as_slice()),
        ("getAnnualMeanByYear", [].as_slice()),
        ("getAnnualMeanColumn", [].as_slice()),
        ("getGreenhouseGasByYear", [].as_slice()),
        ("getGreenhouseGasColumn", [].as_slice()),
        ("getHumanByYear", [].as_slice()),
        ("getHumanColumn", [].as_slice()),
        ("getLandUseByYear", [].as_slice()),
        ("getLandUseColumn", [].as_slice()),
        ("getNaturalByYear", [].as_slice()),
        ("getNaturalColumn", [].as_slice()),
        ("getOrbitByYear", [].as_slice()),
        ("getOrbitColumn", [].as_slice()),
        ("getOzoneByYear", [].as_slice()),
        ("getOzoneColumn", [].as_slice()),
        ("getSolarByYear", [].as_slice()),
        ("getSolarColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["Year", "column name"].as_slice()),
        ("getVolcanismByYear", [].as_slice()),
        ("getVolcanismColumn", [].as_slice()),
        ("getYearColumn", [].as_slice()),
    ].as_slice()),
    ("CloudVariables", [
        ("deleteUserVariable", ["name"].as_slice()),
        ("deleteVariable", ["name", "password"].as_slice()),
        ("getUserVariable", ["name"].as_slice()),
        ("getVariable", ["name", "password"].as_slice()),
        ("listenToUserVariable", ["name", "msgType", "duration"].as_slice()),
        ("listenToVariable", ["name", "msgType", "password", "duration"].as_slice()),
        ("lockVariable", ["name", "password"].as_slice()),
        ("setUserVariable", ["name", "value"].as_slice()),
        ("setVariable", ["name", "value", "password"].as_slice()),
        ("unlockVariable", ["name", "password"].as_slice()),
    ].as_slice()),
    ("ConnectN", [
        ("isFullBoard", [].as_slice()),
        ("isGameOver", [].as_slice()),
        ("newGame", ["row", "column", "numDotsToConnect"].as_slice()),
        ("play", ["row", "column"].as_slice()),
    ].as_slice()),
    ("Coral Growth Anomaly", [
        ("getCoralGrowthAnomalyByYEAR", [].as_slice()),
        ("getCoralGrowthAnomalyColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["YEAR", "column name"].as_slice()),
        ("getYEARColumn", [].as_slice()),
    ].as_slice()),
    ("CoreNLP", [
        ("annotate", ["text", "annotators"].as_slice()),
        ("getAnnotators", [].as_slice()),
    ].as_slice()),
    ("DailyWordGuess", [
        ("getWordList", [].as_slice()),
        ("giveUp", [].as_slice()),
        ("guess", ["word"].as_slice()),
        ("timeRemaining", [].as_slice()),
        ("triesRemaining", [].as_slice()),
    ].as_slice()),
    ("DrugOverdose", [
        ("getNumberAllByYear", [].as_slice()),
        ("getNumberAllColumn", [].as_slice()),
        ("getNumberOpioidAnyByYear", [].as_slice()),
        ("getNumberOpioidAnyColumn", [].as_slice()),
        ("getNumberOpioidCocaineByYear", [].as_slice()),
        ("getNumberOpioidCocaineColumn", [].as_slice()),
        ("getNumberOpioidHeroinByYear", [].as_slice()),
        ("getNumberOpioidHeroinColumn", [].as_slice()),
        ("getNumberOpioidPrescriptionByYear", [].as_slice()),
        ("getNumberOpioidPrescriptionColumn", [].as_slice()),
        ("getNumberOpioidSyntheticByYear", [].as_slice()),
        ("getNumberOpioidSyntheticColumn", [].as_slice()),
        ("getRateAllRaceAmericanIndianOrAlaskaNativeByYear", [].as_slice()),
        ("getRateAllRaceAmericanIndianOrAlaskaNativeColumn", [].as_slice()),
        ("getRateAllRaceAsianOrPacificIslanderByYear", [].as_slice()),
        ("getRateAllRaceAsianOrPacificIslanderColumn", [].as_slice()),
        ("getRateAllRaceBlackByYear", [].as_slice()),
        ("getRateAllRaceBlackColumn", [].as_slice()),
        ("getRateAllRaceHispanicByYear", [].as_slice()),
        ("getRateAllRaceHispanicColumn", [].as_slice()),
        ("getRateAllRaceWhiteByYear", [].as_slice()),
        ("getRateAllRaceWhiteColumn", [].as_slice()),
        ("getRateAllSexFemaleByYear", [].as_slice()),
        ("getRateAllSexFemaleColumn", [].as_slice()),
        ("getRateAllSexMaleByYear", [].as_slice()),
        ("getRateAllSexMaleColumn", [].as_slice()),
        ("getRateAllTotalByYear", [].as_slice()),
        ("getRateAllTotalColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["Year", "column name"].as_slice()),
        ("getYearColumn", [].as_slice()),
    ].as_slice()),
    ("EarthOrbit", [
        ("getEccentricity", ["startyear", "endyear"].as_slice()),
        ("getInsolation", ["startyear", "endyear"].as_slice()),
        ("getLongitude", ["startyear", "endyear"].as_slice()),
        ("getObliquity", ["startyear", "endyear"].as_slice()),
        ("getPrecession", ["startyear", "endyear"].as_slice()),
    ].as_slice()),
    ("Earthquakes", [
        ("byRegion", ["minLatitude", "maxLatitude", "minLongitude", "maxLongitude", "startTime", "endTime", "minMagnitude", "maxMagnitude"].as_slice()),
        ("stop", [].as_slice()),
    ].as_slice()),
    ("Eclipse2017", [
        ("availableStations", ["maxReadingMedian", "maxDistanceFromCenter", "latitude", "longitude", "maxDistanceFromPoint"].as_slice()),
        ("condition", ["stationId"].as_slice()),
        ("conditionHistory", ["stationId", "limit"].as_slice()),
        ("conditionHistoryRange", ["stationId", "startTime", "endTime"].as_slice()),
        ("eclipsePath", [].as_slice()),
        ("pastCondition", ["stationId", "time"].as_slice()),
        ("pastTemperature", ["stationId", "time"].as_slice()),
        ("selectPointBased", [].as_slice()),
        ("selectSectionBased", ["numSections", "perSection"].as_slice()),
        ("stationInfo", ["stationId"].as_slice()),
        ("stations", [].as_slice()),
        ("stationsInfo", [].as_slice()),
        ("temperature", ["stationId"].as_slice()),
        ("temperatureHistory", ["stationId", "limit"].as_slice()),
        ("temperatureHistoryRange", ["stationId", "startTime", "endTime"].as_slice()),
    ].as_slice()),
    ("Execute", [
        ("call", ["fn"].as_slice()),
    ].as_slice()),
    ("Fairbanks Weather", [
        ("getAllDATEValues", [].as_slice()),
        ("getAllPRCPValues", [].as_slice()),
        ("getAllSNOWValues", [].as_slice()),
        ("getAllTMAXValues", [].as_slice()),
        ("getAllTMINValues", [].as_slice()),
        ("getAllTOBSValues", [].as_slice()),
        ("getPRCP", ["DATE"].as_slice()),
        ("getRecord", ["DATE"].as_slice()),
        ("getSNOW", ["DATE"].as_slice()),
        ("getTMAX", ["DATE"].as_slice()),
        ("getTMIN", ["DATE"].as_slice()),
        ("getTOBS", ["DATE"].as_slice()),
    ].as_slice()),
    ("Franklin Temperatures", [
        ("getAllDATEValues", [].as_slice()),
        ("getAllTMAXValues", [].as_slice()),
        ("getAllTMINValues", [].as_slice()),
        ("getAllTOBSValues", [].as_slice()),
        ("getRecord", ["DATE"].as_slice()),
        ("getTMAX", ["DATE"].as_slice()),
        ("getTMIN", ["DATE"].as_slice()),
        ("getTOBS", ["DATE"].as_slice()),
    ].as_slice()),
    ("GDPTrend", [
        ("getChinaByYear", [].as_slice()),
        ("getChinaColumn", [].as_slice()),
        ("getGermanyByYear", [].as_slice()),
        ("getGermanyColumn", [].as_slice()),
        ("getJapanByYear", [].as_slice()),
        ("getJapanColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getUnitedStatesByYear", [].as_slice()),
        ("getUnitedStatesColumn", [].as_slice()),
        ("getValue", ["Year", "column name"].as_slice()),
        ("getYearColumn", [].as_slice()),
    ].as_slice()),
    ("Genius", [
        ("getArtist", ["ID"].as_slice()),
        ("getSong", ["ID"].as_slice()),
        ("getSongLyrics", ["ID"].as_slice()),
        ("getSongsByArtist", ["ID"].as_slice()),
        ("searchSongs", ["query"].as_slice()),
    ].as_slice()),
    ("Geolocation", [
        ("city", ["latitude", "longitude"].as_slice()),
        ("country", ["latitude", "longitude"].as_slice()),
        ("countryCode", ["latitude", "longitude"].as_slice()),
        ("county*", ["latitude", "longitude"].as_slice()),
        ("geolocate", ["address"].as_slice()),
        ("info", ["latitude", "longitude"].as_slice()),
        ("nearbySearch", ["latitude", "longitude", "keyword", "radius"].as_slice()),
        ("state*", ["latitude", "longitude"].as_slice()),
        ("stateCode*", ["latitude", "longitude"].as_slice()),
        ("streetAddress", ["address"].as_slice()),
        ("timezone", ["address"].as_slice()),
    ].as_slice()),
    ("GlobalLandTemperature", [
        ("get10YearAverage", ["Date"].as_slice()),
        ("getAll10YearAverageValues", [].as_slice()),
        ("getAllAnnualValues", [].as_slice()),
        ("getAllDateValues", [].as_slice()),
        ("getAllMonthlyValues", [].as_slice()),
        ("getAnnual", ["Date"].as_slice()),
        ("getMonthly", ["Date"].as_slice()),
        ("getRecord", ["Date"].as_slice()),
    ].as_slice()),
    ("GoogleMaps", [
        ("getDistance", ["startLatitude", "startLongitude", "endLatitude", "endLongitude"].as_slice()),
        ("getEarthCoordinates", ["x", "y"].as_slice()),
        ("getImageCoordinates", ["latitude", "longitude"].as_slice()),
        ("getLatitude", ["y"].as_slice()),
        ("getLatitudeFromY", ["y"].as_slice()),
        ("getLongitude", ["x"].as_slice()),
        ("getLongitudeFromX", ["x"].as_slice()),
        ("getMap", ["latitude", "longitude", "width", "height", "zoom"].as_slice()),
        ("getSatelliteMap", ["latitude", "longitude", "width", "height", "zoom"].as_slice()),
        ("getTerrainMap", ["latitude", "longitude", "width", "height", "zoom"].as_slice()),
        ("getXFromLongitude", ["longitude"].as_slice()),
        ("getYFromLatitude", ["latitude"].as_slice()),
        ("maxLatitude", [].as_slice()),
        ("maxLongitude", [].as_slice()),
        ("minLatitude", [].as_slice()),
        ("minLongitude", [].as_slice()),
    ].as_slice()),
    ("GoogleStreetView", [
        ("getInfo", ["latitude", "longitude", "fieldofview", "heading", "pitch"].as_slice()),
        ("getInfoFromAddress", ["location", "fieldofview", "heading", "pitch"].as_slice()),
        ("getView", ["latitude", "longitude", "width", "height", "fieldofview", "heading", "pitch"].as_slice()),
        ("getViewFromAddress", ["location", "width", "height", "fieldofview", "heading", "pitch"].as_slice()),
        ("getViewFromLatLong", ["latitude", "longitude", "width", "height", "fieldofview", "heading", "pitch"].as_slice()),
        ("isAvailable", ["latitude", "longitude", "fieldofview", "heading", "pitch"].as_slice()),
        ("isAvailableFromAddress", ["location", "fieldofview", "heading", "pitch"].as_slice()),
    ].as_slice()),
    ("HPV Vaccination", [
        ("getAllSexValues", [].as_slice()),
        ("getAnnualPercentChangeAPC", ["Sex"].as_slice()),
        ("getAverageAnnualPercentChangeAAPC", ["Sex"].as_slice()),
        ("getHealthyPeople2020TargetForSex", ["Sex"].as_slice()),
        ("getPercent", ["Sex"].as_slice()),
        ("getPercentTrendLine", ["Sex"].as_slice()),
        ("getTable", [].as_slice()),
        ("getYear", ["Sex"].as_slice()),
    ].as_slice()),
    ("Hangman", [
        ("getCurrentlyKnownWord", [].as_slice()),
        ("getWrongCount", [].as_slice()),
        ("guess", ["letter"].as_slice()),
        ("isWordGuessed", [].as_slice()),
        ("setWord", ["word"].as_slice()),
    ].as_slice()),
    ("HistoricalTemperature", [
        ("annualAnomaly", ["region"].as_slice()),
        ("fiveYearAnomaly", ["region"].as_slice()),
        ("monthlyAnomaly", ["region"].as_slice()),
        ("tenYearAnomaly", ["region"].as_slice()),
        ("twentyYearAnomaly", ["region"].as_slice()),
    ].as_slice()),
    ("HumanMortalityDatabase", [
        ("getAllData", [].as_slice()),
        ("getAllDataForCountry", ["country"].as_slice()),
        ("getCategories", [].as_slice()),
        ("getCountries", [].as_slice()),
        ("getGenders", [].as_slice()),
        ("getTimeSeries", ["country", "gender", "category"].as_slice()),
    ].as_slice()),
    ("HurricaneData", [
        ("getHurricaneData", ["name", "year"].as_slice()),
        ("getHurricanesInYear", ["year"].as_slice()),
        ("getYearsWithHurricaneNamed", ["name"].as_slice()),
    ].as_slice()),
    ("IceCoreData", [
        ("getCarbonDioxideData", ["core", "startyear", "endyear"].as_slice()),
        ("getDataAvailability", [].as_slice()),
        ("getDelta18OData", ["core", "startyear", "endyear"].as_slice()),
        ("getDeuteriumData", ["core", "startyear", "endyear"].as_slice()),
        ("getIceCoreMetadata", ["core"].as_slice()),
        ("getIceCoreNames", [].as_slice()),
        ("getTemperatureData", ["core", "startyear", "endyear"].as_slice()),
    ].as_slice()),
    ("IoTScape", [
        ("getDevices", ["service"].as_slice()),
        ("getMessageTypes", ["service"].as_slice()),
        ("getServices", [].as_slice()),
        ("send", ["service", "id", "command"].as_slice()),
    ].as_slice()),
    ("KeyValueStore", [
        ("child", ["key", "password"].as_slice()),
        ("delete", ["key", "password"].as_slice()),
        ("get", ["key", "password"].as_slice()),
        ("parent", ["key"].as_slice()),
        ("put", ["key", "value", "password"].as_slice()),
    ].as_slice()),
    ("LIDARSensor", [
        ("getDevices", [].as_slice()),
        ("getRange", ["id"].as_slice()),
        ("listen", ["id"].as_slice()),
    ].as_slice()),
    ("LandOceanTemperatureIndex", [
        ("getAllAprValues", [].as_slice()),
        ("getAllAugValues", [].as_slice()),
        ("getAllDJFValues", [].as_slice()),
        ("getAllDNValues", [].as_slice()),
        ("getAllDecValues", [].as_slice()),
        ("getAllFebValues", [].as_slice()),
        ("getAllJDValues", [].as_slice()),
        ("getAllJJAValues", [].as_slice()),
        ("getAllJanValues", [].as_slice()),
        ("getAllJulValues", [].as_slice()),
        ("getAllJunValues", [].as_slice()),
        ("getAllMAMValues", [].as_slice()),
        ("getAllMarValues", [].as_slice()),
        ("getAllMayValues", [].as_slice()),
        ("getAllNovValues", [].as_slice()),
        ("getAllOctValues", [].as_slice()),
        ("getAllSONValues", [].as_slice()),
        ("getAllSepValues", [].as_slice()),
        ("getAllYearValues", [].as_slice()),
        ("getApr", ["Year"].as_slice()),
        ("getAug", ["Year"].as_slice()),
        ("getDJF", ["Year"].as_slice()),
        ("getDN", ["Year"].as_slice()),
        ("getDec", ["Year"].as_slice()),
        ("getFeb", ["Year"].as_slice()),
        ("getJD", ["Year"].as_slice()),
        ("getJJA", ["Year"].as_slice()),
        ("getJan", ["Year"].as_slice()),
        ("getJul", ["Year"].as_slice()),
        ("getJun", ["Year"].as_slice()),
        ("getMAM", ["Year"].as_slice()),
        ("getMar", ["Year"].as_slice()),
        ("getMay", ["Year"].as_slice()),
        ("getNov", ["Year"].as_slice()),
        ("getOct", ["Year"].as_slice()),
        ("getRecord", ["Year"].as_slice()),
        ("getSON", ["Year"].as_slice()),
        ("getSep", ["Year"].as_slice()),
    ].as_slice()),
    ("MaunaLoaCO2Data", [
        ("getCO2Trend", ["startyear", "endyear"].as_slice()),
        ("getRawCO2", ["startyear", "endyear"].as_slice()),
    ].as_slice()),
    ("MetMuseum", [
        ("advancedSearch", ["field", "query", "skip", "limit"].as_slice()),
        ("fields", [].as_slice()),
        ("getImageUrls", ["id"].as_slice()),
        ("getInfo", ["id"].as_slice()),
        ("searchByArtistDisplayBio", ["query"].as_slice()),
        ("searchByArtistDisplayName", ["query"].as_slice()),
        ("searchByClassification", ["query"].as_slice()),
        ("searchByCountry", ["query"].as_slice()),
        ("searchByCreditLine", ["query"].as_slice()),
        ("searchByDepartment", ["query"].as_slice()),
        ("searchByDimensions", ["query"].as_slice()),
        ("searchByIsHighlight", ["query"].as_slice()),
        ("searchByMedium", ["query"].as_slice()),
        ("searchByObjectDate", ["query"].as_slice()),
        ("searchByObjectName", ["query"].as_slice()),
        ("searchByRepository", ["query"].as_slice()),
        ("searchByTitle", ["query"].as_slice()),
    ].as_slice()),
    ("MetalDetector", [
        ("dig", ["id"].as_slice()),
        ("getDevices", [].as_slice()),
        ("getIntensity", ["id"].as_slice()),
        ("listen", ["id"].as_slice()),
    ].as_slice()),
    ("MovieDB", [
        ("getImage", ["path"].as_slice()),
        ("movieBackdropPath", ["id"].as_slice()),
        ("movieBudget", ["id"].as_slice()),
        ("movieCastCharacters", ["id"].as_slice()),
        ("movieCastNames", ["id"].as_slice()),
        ("movieCastPersonIDs", ["id"].as_slice()),
        ("movieCastProfilePaths", ["id"].as_slice()),
        ("movieCrewJobs", ["id"].as_slice()),
        ("movieCrewNames", ["id"].as_slice()),
        ("movieCrewPersonIDs", ["id"].as_slice()),
        ("movieCrewProfilePaths", ["id"].as_slice()),
        ("movieGenres", ["id"].as_slice()),
        ("movieOriginalLanguage", ["id"].as_slice()),
        ("movieOriginalTitle", ["id"].as_slice()),
        ("movieOverview", ["id"].as_slice()),
        ("moviePopularity", ["id"].as_slice()),
        ("moviePosterPath", ["id"].as_slice()),
        ("movieProductionCompanies", ["id"].as_slice()),
        ("movieProductionCountries", ["id"].as_slice()),
        ("movieReleaseDate", ["id"].as_slice()),
        ("movieRevenue", ["id"].as_slice()),
        ("movieRuntime", ["id"].as_slice()),
        ("movieSpokenLanguages", ["id"].as_slice()),
        ("movieTagline", ["id"].as_slice()),
        ("movieTitle", ["id"].as_slice()),
        ("movieVoteAverage", ["id"].as_slice()),
        ("movieVoteCount", ["id"].as_slice()),
        ("personBiography", ["id"].as_slice()),
        ("personBirthday", ["id"].as_slice()),
        ("personCastCharacters", ["id"].as_slice()),
        ("personCastMovieIDs", ["id"].as_slice()),
        ("personCastOriginalTitles", ["id"].as_slice()),
        ("personCastPosterPaths", ["id"].as_slice()),
        ("personCastReleaseDates", ["id"].as_slice()),
        ("personCastTitles", ["id"].as_slice()),
        ("personCrewJobs", ["id"].as_slice()),
        ("personCrewMovieIDs", ["id"].as_slice()),
        ("personCrewOriginalTitles", ["id"].as_slice()),
        ("personCrewPosterPaths", ["id"].as_slice()),
        ("personCrewReleaseDates", ["id"].as_slice()),
        ("personCrewTitles", ["id"].as_slice()),
        ("personDeathday", ["id"].as_slice()),
        ("personGender", ["id"].as_slice()),
        ("personImageAspectRatios", ["id"].as_slice()),
        ("personImageFilePaths", ["id"].as_slice()),
        ("personImageHeights", ["id"].as_slice()),
        ("personImageVoteCounts", ["id"].as_slice()),
        ("personImageWidths", ["id"].as_slice()),
        ("personName", ["id"].as_slice()),
        ("personPlaceOfBirth", ["id"].as_slice()),
        ("personPopularity", ["id"].as_slice()),
        ("personProfilePath", ["id"].as_slice()),
        ("searchMovie", ["title"].as_slice()),
        ("searchPerson", ["name"].as_slice()),
    ].as_slice()),
    ("NASA", [
        ("apod", [].as_slice()),
        ("apodDetails", [].as_slice()),
        ("apodMedia", [].as_slice()),
        ("marsHighTemp", [].as_slice()),
        ("marsLowTemp", [].as_slice()),
        ("marsWeather", [].as_slice()),
    ].as_slice()),
    ("NPlayer", [
        ("endTurn", ["next"].as_slice()),
        ("getActive", [].as_slice()),
        ("getN", [].as_slice()),
        ("getNext", [].as_slice()),
        ("getPrevious", [].as_slice()),
        ("start", [].as_slice()),
    ].as_slice()),
    ("NewYorkPublicLibrary", [
        ("getDetails", ["uuid"].as_slice()),
        ("getImage", ["itemID"].as_slice()),
        ("search", ["term", "perPage", "page"].as_slice()),
    ].as_slice()),
    ("NewYorkTimes", [
        ("getArticleSections", [].as_slice()),
        ("getArticlesWithConcept", ["concept"].as_slice()),
        ("getBestSellerLists", [].as_slice()),
        ("getBestSellers", ["list", "date"].as_slice()),
        ("getConceptInfo", ["concept"].as_slice()),
        ("getConceptTypes", [].as_slice()),
        ("getCriticsPicks", ["offset"].as_slice()),
        ("getLatestArticles", ["section"].as_slice()),
        ("getMostEmailedArticles", ["period"].as_slice()),
        ("getMostSharedArticles", ["period"].as_slice()),
        ("getMostViewedArticles", ["period"].as_slice()),
        ("getMovieCriticInfo", ["name"].as_slice()),
        ("getMovieCritics", [].as_slice()),
        ("getMovieReviews", ["offset"].as_slice()),
        ("getMovieReviewsByCritic", ["critic", "offset"].as_slice()),
        ("getTopBestSellers", ["date"].as_slice()),
        ("getTopStories", ["section"].as_slice()),
        ("searchArticles", ["query", "offset"].as_slice()),
        ("searchBestSellers", ["title", "author", "offset"].as_slice()),
        ("searchConcepts", ["query"].as_slice()),
        ("searchMovieReviews", ["query", "offset"].as_slice()),
    ].as_slice()),
    ("OceanData", [
        ("getDeepOceanTemp", ["startYear", "endYear"].as_slice()),
        ("getOxygenRatio", ["startYear", "endYear"].as_slice()),
        ("getSeaLevel", ["startYear", "endYear"].as_slice()),
        ("getSurfaceTemp", ["startYear", "endYear"].as_slice()),
    ].as_slice()),
    ("PaleoceanOxygenIsotopes", [
        ("getAverageSedimentationRates", ["startyear", "endyear"].as_slice()),
        ("getDelta18O", ["startyear", "endyear"].as_slice()),
        ("getDelta18OError", ["startyear", "endyear"].as_slice()),
        ("getNormalizedSedimentationRates", ["startyear", "endyear"].as_slice()),
    ].as_slice()),
    ("ParallelDots", [
        ("getAbuse", ["text"].as_slice()),
        ("getEmotion", ["text"].as_slice()),
        ("getIntent", ["text"].as_slice()),
        ("getKeywords", ["text"].as_slice()),
        ("getNamedEntities", ["text"].as_slice()),
        ("getSarcasmProbability", ["text"].as_slice()),
        ("getSentiment", ["text"].as_slice()),
        ("getSimilarity", ["text1", "text2"].as_slice()),
        ("getTaxonomy", ["text"].as_slice()),
    ].as_slice()),
    ("People", [
        ("getAgeByName", [].as_slice()),
        ("getAgeColumn", [].as_slice()),
        ("getNameColumn", [].as_slice()),
        ("getSexByName", [].as_slice()),
        ("getSexColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["name", "column name"].as_slice()),
    ].as_slice()),
    ("PhoneIoT", [
        ("addButton", ["device", "x", "y", "width", "height", "text", "options"].as_slice()),
        ("addImageDisplay", ["device", "x", "y", "width", "height", "options"].as_slice()),
        ("addJoystick", ["device", "x", "y", "width", "options"].as_slice()),
        ("addLabel", ["device", "x", "y", "text", "options"].as_slice()),
        ("addRadioButton", ["device", "x", "y", "text", "options"].as_slice()),
        ("addSlider", ["device", "x", "y", "width", "options"].as_slice()),
        ("addTextField", ["device", "x", "y", "width", "height", "options"].as_slice()),
        ("addToggle", ["device", "x", "y", "text", "options"].as_slice()),
        ("addTouchpad", ["device", "x", "y", "width", "height", "options"].as_slice()),
        ("authenticate", ["device"].as_slice()),
        ("clearControls", ["device"].as_slice()),
        ("getAccelerometer", ["device"].as_slice()),
        ("getAltitude", ["device"].as_slice()),
        ("getBearing", ["device"].as_slice()),
        ("getColor", ["red", "green", "blue", "alpha"].as_slice()),
        ("getCompassCardinalDirection", ["device"].as_slice()),
        ("getCompassDirection", ["device"].as_slice()),
        ("getCompassHeading", ["device"].as_slice()),
        ("getFacingDirection", ["device"].as_slice()),
        ("getGPSHeading", ["device"].as_slice()),
        ("getGameRotation", ["device"].as_slice()),
        ("getGravity", ["device"].as_slice()),
        ("getGyroscope", ["device"].as_slice()),
        ("getImage", ["device", "id"].as_slice()),
        ("getJoystickVector", ["device", "id"].as_slice()),
        ("getLevel", ["device", "id"].as_slice()),
        ("getLightLevel", ["device"].as_slice()),
        ("getLinearAcceleration", ["device"].as_slice()),
        ("getLocation", ["device"].as_slice()),
        ("getMagneticField", ["device"].as_slice()),
        ("getMicrophoneLevel", ["device"].as_slice()),
        ("getOrientation", ["device"].as_slice()),
        ("getPosition", ["device", "id"].as_slice()),
        ("getPressure", ["device"].as_slice()),
        ("getProximity", ["device"].as_slice()),
        ("getRelativeHumidity", ["device"].as_slice()),
        ("getRotation", ["device"].as_slice()),
        ("getSensors", [].as_slice()),
        ("getStepCount", ["device"].as_slice()),
        ("getTemperature", ["device"].as_slice()),
        ("getText", ["device", "id"].as_slice()),
        ("getToggleState", ["device", "id"].as_slice()),
        ("isPressed", ["device", "id"].as_slice()),
        ("listenToGUI", ["device"].as_slice()),
        ("listenToSensors", ["device", "sensors"].as_slice()),
        ("magnitude", ["vec"].as_slice()),
        ("normalize", ["vec"].as_slice()),
        ("removeControl", ["device", "id"].as_slice()),
        ("setCredentials", ["device", "password"].as_slice()),
        ("setImage", ["device", "id", "img"].as_slice()),
        ("setLevel", ["device", "id", "value"].as_slice()),
        ("setText", ["device", "id", "text"].as_slice()),
        ("setToggleState", ["device", "id", "state"].as_slice()),
        ("stopSensors", ["device"].as_slice()),
    ].as_slice()),
    ("Pixabay", [
        ("getImage", ["url"].as_slice()),
        ("searchAll", ["keywords", "maxHeight", "minHeight"].as_slice()),
        ("searchIllustration", ["keywords", "maxHeight", "minHeight"].as_slice()),
        ("searchPhoto", ["keywords", "maxHeight", "minHeight"].as_slice()),
    ].as_slice()),
    ("PositionSensor", [
        ("getDevices", [].as_slice()),
        ("getHeading", ["id"].as_slice()),
        ("getPosition", ["id"].as_slice()),
        ("getX", ["id"].as_slice()),
        ("getY", ["id"].as_slice()),
        ("getZ", ["id"].as_slice()),
        ("listen", ["id"].as_slice()),
    ].as_slice()),
    ("ProjectGutenberg", [
        ("getInfo", ["ID"].as_slice()),
        ("getText", ["ID"].as_slice()),
        ("search", ["field", "text"].as_slice()),
    ].as_slice()),
    ("PublicRoles", [
        ("getPublicRoleId", [].as_slice()),
        ("requestPublicRoleId", [].as_slice()),
    ].as_slice()),
    ("RainViewer", [
        ("getColorSchemes", [].as_slice()),
        ("getOverlay", ["latitude", "longitude", "width", "height", "zoom", "timeOffset", "options"].as_slice()),
        ("getTimeOffsets", [].as_slice()),
    ].as_slice()),
    ("RoboScape", [
        ("eavesdrop", ["robots"].as_slice()),
        ("getRobots", [].as_slice()),
        ("listen", ["robots"].as_slice()),
        ("send", ["robot", "command"].as_slice()),
    ].as_slice()),
    ("S1", [
        ("get1222021", ["Well A"].as_slice()),
        ("get172", ["Well A"].as_slice()),
        ("getAllWellAValues", [].as_slice()),
        ("getTable", [].as_slice()),
    ].as_slice()),
    ("ServiceCreation", [
        ("createServiceFromTable", ["name", "data", "options"].as_slice()),
        ("deleteService", ["name"].as_slice()),
        ("getCreateFromTableOptions", ["data"].as_slice()),
    ].as_slice()),
    ("SimpleHangman", [
        ("getCurrentlyKnownWord", [].as_slice()),
        ("getWrongCount", [].as_slice()),
        ("guess", ["letter"].as_slice()),
        ("isWordGuessed", [].as_slice()),
        ("restart", ["word"].as_slice()),
    ].as_slice()),
    ("Smithsonian", [
        ("getImage", ["id"].as_slice()),
        ("search", ["term", "count", "skip"].as_slice()),
        ("searchImageContent", ["term", "count", "skip"].as_slice()),
    ].as_slice()),
    ("StarMap", [
        ("arcHourMinSecToDeg", ["arcHour", "arcMin", "arcSec"].as_slice()),
        ("findObject", ["name"].as_slice()),
        ("getImage", ["right_ascension", "declination", "arcseconds_per_pixel", "options", "width", "height"].as_slice()),
    ].as_slice()),
    ("StudentPerformance", [
        ("getAllGenderValues", [].as_slice()),
        ("getLunch", ["gender"].as_slice()),
        ("getMathScore", ["gender"].as_slice()),
        ("getParentalLevelOfEducation", ["gender"].as_slice()),
        ("getRaceEthnicity", ["gender"].as_slice()),
        ("getReadingScore", ["gender"].as_slice()),
        ("getTable", [].as_slice()),
        ("getTestPreparationCourse", ["gender"].as_slice()),
        ("getWritingScore", ["gender"].as_slice()),
    ].as_slice()),
    ("SummerOlympicMedals", [
        ("getAllYearValues", [].as_slice()),
        ("getAthlete", ["Year"].as_slice()),
        ("getCityForYear", ["Year"].as_slice()),
        ("getCountry", ["Year"].as_slice()),
        ("getDiscipline", ["Year"].as_slice()),
        ("getEvent", ["Year"].as_slice()),
        ("getGender", ["Year"].as_slice()),
        ("getMedal", ["Year"].as_slice()),
        ("getSport", ["Year"].as_slice()),
    ].as_slice()),
    ("TemperatureDatabase", [
        ("getAerosolsByYear", [].as_slice()),
        ("getAerosolsColumn", [].as_slice()),
        ("getAllByYear", [].as_slice()),
        ("getAllColumn", [].as_slice()),
        ("getAnnualMeanByYear", [].as_slice()),
        ("getAnnualMeanColumn", [].as_slice()),
        ("getGreenhouseGasByYear", [].as_slice()),
        ("getGreenhouseGasColumn", [].as_slice()),
        ("getHumanByYear", [].as_slice()),
        ("getHumanColumn", [].as_slice()),
        ("getLandUseByYear", [].as_slice()),
        ("getLandUseColumn", [].as_slice()),
        ("getNaturalByYear", [].as_slice()),
        ("getNaturalColumn", [].as_slice()),
        ("getOrbitByYear", [].as_slice()),
        ("getOrbitColumn", [].as_slice()),
        ("getOzoneByYear", [].as_slice()),
        ("getOzoneColumn", [].as_slice()),
        ("getSolarByYear", [].as_slice()),
        ("getSolarColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["Year", "column name"].as_slice()),
        ("getVolcanismByYear", [].as_slice()),
        ("getVolcanismColumn", [].as_slice()),
        ("getYearColumn", [].as_slice()),
    ].as_slice()),
    ("TheMapotakes's First Service", [
        ("getAwayScoreSum", [].as_slice()),
        ("getDateColumn", [].as_slice()),
        ("getHomeScoreSum", [].as_slice()),
    ].as_slice()),
    ("Thingspeak", [
        ("channelDetails", ["id"].as_slice()),
        ("channelFeed", ["id", "numResult"].as_slice()),
        ("privateChannelFeed", ["id", "numResult", "apiKey"].as_slice()),
        ("searchByLocation", ["latitude", "longitude", "distance", "limit", "updatedSince"].as_slice()),
        ("searchByTag", ["tag", "limit", "updatedSince"].as_slice()),
        ("searchByTagAndLocation", ["tag", "latitude", "longitude", "distance", "limit", "updatedSince"].as_slice()),
    ].as_slice()),
    ("ThisXDoesNotExist", [
        ("getArtwork", [].as_slice()),
        ("getCat", [].as_slice()),
        ("getCongressPerson", [].as_slice()),
        ("getFursona", [].as_slice()),
        ("getHomeInterior", [].as_slice()),
        ("getHorse", [].as_slice()),
        ("getPerson", [].as_slice()),
        ("getPony", [].as_slice()),
        ("getWaifu", [].as_slice()),
    ].as_slice()),
    ("Tobacco Consumption", [
        ("getAllMeasureValues", [].as_slice()),
        ("getCountry", ["Measure"].as_slice()),
        ("getValue", ["Measure"].as_slice()),
        ("getYEA", ["Measure"].as_slice()),
        ("getYear", ["Measure"].as_slice()),
    ].as_slice()),
    ("Translation", [
        ("detectLanguage", ["text"].as_slice()),
        ("getSupportedLanguages", [].as_slice()),
        ("toEnglish", ["text"].as_slice()),
        ("translate", ["text", "from", "to"].as_slice()),
    ].as_slice()),
    ("Trivia", [
        ("getRandomQuestion", [].as_slice()),
        ("random", [].as_slice()),
    ].as_slice()),
    ("TwentyQuestions", [
        ("answer", ["answer"].as_slice()),
        ("gameStarted", [].as_slice()),
        ("guess", ["guess"].as_slice()),
        ("restart", [].as_slice()),
        ("start", ["answer"].as_slice()),
    ].as_slice()),
    ("Twitter", [
        ("favorites", ["screenName", "count"].as_slice()),
        ("favoritesCount", ["screenName"].as_slice()),
        ("followers", ["screenName"].as_slice()),
        ("recentTweets", ["screenName", "count"].as_slice()),
        ("search", ["keyword", "count"].as_slice()),
        ("tweets", ["screenName"].as_slice()),
        ("tweetsPerDay", ["screenName"].as_slice()),
    ].as_slice()),
    ("Vaping", [
        ("getAllMeasureValues", [].as_slice()),
        ("getCountry", ["Measure"].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["Measure"].as_slice()),
        ("getYear", ["Measure"].as_slice()),
    ].as_slice()),
    ("Vostok Temperatures", [
        ("getAllTemperatureValues", [].as_slice()),
        ("getAllYearValues", [].as_slice()),
        ("getRecord", ["Year"].as_slice()),
        ("getTemperature", ["Year"].as_slice()),
    ].as_slice()),
    ("Water Quality", [
        ("getAllWellValues", [].as_slice()),
        ("getDate", ["Well"].as_slice()),
        ("getQuality", ["Well"].as_slice()),
        ("getTable", [].as_slice()),
    ].as_slice()),
    ("WaterWatch", [
        ("gageHeight", ["minLatitude", "maxLatitude", "minLongitude", "maxLongitude"].as_slice()),
        ("stop", [].as_slice()),
        ("streamFlow", ["minLatitude", "maxLatitude", "minLongitude", "maxLongitude"].as_slice()),
        ("waterTemp", ["minLatitude", "maxLatitude", "minLongitude", "maxLongitude"].as_slice()),
    ].as_slice()),
    ("WaypointList", [
        ("getDevices", [].as_slice()),
        ("getNextWaypoint", ["id"].as_slice()),
        ("listen", ["id"].as_slice()),
    ].as_slice()),
    ("Weather", [
        ("description", ["latitude", "longitude"].as_slice()),
        ("humidity", ["latitude", "longitude"].as_slice()),
        ("icon", ["latitude", "longitude"].as_slice()),
        ("temp", ["latitude", "longitude"].as_slice()),
        ("temperature", ["latitude", "longitude"].as_slice()),
        ("windAngle", ["latitude", "longitude"].as_slice()),
        ("windSpeed", ["latitude", "longitude"].as_slice()),
    ].as_slice()),
    ("Well Data", [
        ("get1222021", ["Well A"].as_slice()),
        ("get172", ["Well A"].as_slice()),
        ("getAllWellAValues", [].as_slice()),
        ("getTable", [].as_slice()),
    ].as_slice()),
    ("Wildcam", [
        ("getCameras", ["latitude", "longitude", "radius"].as_slice()),
        ("getImage", ["entry"].as_slice()),
        ("getSpeciesList", [].as_slice()),
        ("search", ["startDate", "stopDate", "species", "latitude", "longitude", "radius"].as_slice()),
        ("searchByCamera", ["startDate", "stopDate", "species", "camera"].as_slice()),
    ].as_slice()),
    ("WordGuess", [
        ("getWordList", ["length"].as_slice()),
        ("giveUp", [].as_slice()),
        ("guess", ["word"].as_slice()),
        ("start", ["length"].as_slice()),
    ].as_slice()),
    ("brian's First Service", [
        ("getAwayScoreByDate", [].as_slice()),
        ("getAwayScoreColumn", [].as_slice()),
        ("getAwayTeamByDate", [].as_slice()),
        ("getAwayTeamColumn", [].as_slice()),
        ("getCityByDate", [].as_slice()),
        ("getCityColumn", [].as_slice()),
        ("getCountryColumn", [].as_slice()),
        ("getDateColumn", [].as_slice()),
        ("getHomeScoreByDate", [].as_slice()),
        ("getHomeScoreColumn", [].as_slice()),
        ("getHomeTeamByDate", [].as_slice()),
        ("getHomeTeamColumn", [].as_slice()),
    ].as_slice()),
    ("brian's soccer service", [
        ("getAwayScoreByDate", [].as_slice()),
        ("getAwayScoreColumn", [].as_slice()),
        ("getAwayTeamByDate", [].as_slice()),
        ("getAwayTeamColumn", [].as_slice()),
        ("getCityByDate", [].as_slice()),
        ("getCityColumn", [].as_slice()),
        ("getCountryByDate", [].as_slice()),
        ("getCountryColumn", [].as_slice()),
        ("getDateColumn", [].as_slice()),
        ("getHomeScoreByDate", [].as_slice()),
        ("getHomeScoreColumn", [].as_slice()),
        ("getHomeTeamByDate", [].as_slice()),
        ("getHomeTeamColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["date", "column name"].as_slice()),
    ].as_slice()),
    ("cbradyisTestingFromCSV", [
        ("getAreaByIndex", [].as_slice()),
        ("getAreaColumn", [].as_slice()),
        ("getIndexColumn", [].as_slice()),
        ("getPerimeterByIndex", [].as_slice()),
        ("getPerimeterColumn", [].as_slice()),
        ("getRadiusByIndex", [].as_slice()),
        ("getRadiusColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["index", "column name"].as_slice()),
    ].as_slice()),
    ("classhole", [
        ("getAColumn", [].as_slice()),
        ("getBByA", [].as_slice()),
        ("getBColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["a", "column name"].as_slice()),
    ].as_slice()),
    ("coreys-soccer-wtih-options", [
        ("getAwayScoreByDate", [].as_slice()),
        ("getAwayScoreColumn", [].as_slice()),
        ("getAwayTeamByDate", [].as_slice()),
        ("getAwayTeamColumn", [].as_slice()),
        ("getCityByDate", [].as_slice()),
        ("getCityColumn", [].as_slice()),
        ("getCountryByDate", [].as_slice()),
        ("getCountryColumn", [].as_slice()),
        ("getDateColumn", [].as_slice()),
        ("getHomeScoreByDate", [].as_slice()),
        ("getHomeScoreColumn", [].as_slice()),
        ("getHomeTeamByDate", [].as_slice()),
        ("getHomeTeamColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["date", "column name"].as_slice()),
    ].as_slice()),
    ("dummy", [
        ("get12ByA", [].as_slice()),
        ("get12Column", [].as_slice()),
        ("getAColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["A", "column name"].as_slice()),
    ].as_slice()),
    ("empty service", [
        ("get0By0", [].as_slice()),
        ("get0Column", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["0", "column name"].as_slice()),
    ].as_slice()),
    ("myfirstservice", [
        ("getAForA", ["a"].as_slice()),
        ("getAllAValues", [].as_slice()),
        ("getBForA", ["a"].as_slice()),
        ("getTable", [].as_slice()),
    ].as_slice()),
    ("myservice", [
        ("getAColumn", [].as_slice()),
        ("getBByA", [].as_slice()),
        ("getBColumn", [].as_slice()),
        ("getCByA", [].as_slice()),
        ("getCColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["a", "column name"].as_slice()),
    ].as_slice()),
    ("myservice1", [
        ("get1ByA", [].as_slice()),
        ("get1Column", [].as_slice()),
        ("getAColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["a", "column name"].as_slice()),
    ].as_slice()),
    ("soccer", [
        ("getAwayScoreByDate", [].as_slice()),
        ("getAwayScoreColumn", [].as_slice()),
        ("getAwayTeamByDate", [].as_slice()),
        ("getAwayTeamColumn", [].as_slice()),
        ("getCityByDate", [].as_slice()),
        ("getCityColumn", [].as_slice()),
        ("getCountryByDate", [].as_slice()),
        ("getCountryColumn", [].as_slice()),
        ("getDateColumn", [].as_slice()),
        ("getHomeScoreByDate", [].as_slice()),
        ("getHomeScoreColumn", [].as_slice()),
        ("getHomeTeamByDate", [].as_slice()),
        ("getHomeTeamColumn", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["date", "column name"].as_slice()),
    ].as_slice()),
    ("test1", [
        ("get1Column", [].as_slice()),
        ("get2By1", [].as_slice()),
        ("get2Column", [].as_slice()),
        ("get3By1", [].as_slice()),
        ("get3Column", [].as_slice()),
        ("getTable", [].as_slice()),
        ("getValue", ["1", "column name"].as_slice()),
    ].as_slice()),
].as_slice();